name: chebfun Tests
on: [push]
jobs:
  r2021a-matlab-chebtest:
    name: R2021a Matlab chebtest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021a
          products: Optimization_Toolbox
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('.'); results = chebtest; assert(all([results{:,3}] > 0))

  r2021b-matlab-chebtest:
    name: R2021b Matlab chebtest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021b
          products: Optimization_Toolbox
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('.'); results = chebtest; assert(all([results{:,3}] > 0))

  r2021b-matlab-no-toolbox-chebtest:
    name: R2021b Matlab no toolboxes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021b

  r2025a-matlab-chebtest:
    name: R2025a Matlab chebtest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2025a
          products: Optimization_Toolbox
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('.'); results = chebtest; assert(all([results{:,3}] > 0))
