name: chebfun Tests
on: [push]
jobs:
  chebfun-test:
    name: Run chebfun tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2021a
      - name: Run commands
        uses: matlab-actions/run-command@v2
        with:
          command: addpath('.'); results = chebtest; assert(all([results{:,3}] > 0))
